# Generated by Django 5.0.3 on 2024-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='shop_number',
            field=models.IntegerField(default=0),
        ),
    ]
