# Generated by Django 5.0.3 on 2024-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_phone_users_shop_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='akp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
