# Generated by Django 5.0.3 on 2024-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_users_ball_users_chat_id_users_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lang',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
