# Generated by Django 4.2.3 on 2024-04-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_users_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('fullname', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('lang', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('shop_number', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('akp', models.CharField(blank=True, max_length=8, null=True)),
                ('ball', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1', models.IntegerField(blank=True, null=True)),
                ('int2', models.IntegerField(blank=True, null=True)),
                ('int3', models.IntegerField(blank=True, null=True)),
                ('int4', models.IntegerField(blank=True, null=True)),
                ('int5', models.IntegerField(blank=True, null=True)),
                ('str1', models.TextField(blank=True, null=True)),
                ('str2', models.TextField(blank=True, null=True)),
                ('str3', models.TextField(blank=True, null=True)),
                ('str4', models.TextField(blank=True, null=True)),
                ('str5', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
